### ISSUE TITLE
支持慢调用和错误调用 的链路采集。

### ISSUE THREAD

**Issue by myfairys** [yihuabaowei/X-PaaS#24]
总体思路 很复杂。具体见线下文档。

主要要求：
1. 在配置中增加参数，设置慢/错调用 采集支持与否。同时要设置慢调用的识别时长，如10秒。
2. 修改agent逻辑，当遇到慢调用和错误调用，本次span以及上游span链路全部上报，忽略采样设置。

@xjlybx 请主导。

**Comment by myfairys** [comment]
研发完成

**Comment by xjlybx** [comment]
你还让我给你review啊







在 2021-02-22 14:21:26，"张虎" <notifications@github.com> 写道：

研发完成
